# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jeportie <jeportie@42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/12 17:28:24 by jeportie          #+#    #+#              #
#    Updated: 2025/08/25 15:35:16 by jeportie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:

  frontend:
    container_name: frontend
    env_file:
      - services/frontend/.env.frontend
    volumes:
      - ./services/frontend/src:/app/src:delegated
      - ./services/frontend/public:/app/public:delegated
    networks:
      - transc
    build: ./services/frontend
    restart: always

  api:
    container_name: api
    env_file:
      - services/api/.env.api
    volumes:
      - ./data/sqlite:/data:delegated
      - ./services/frontend/public:/app/public:ro
    networks:
      - transc
    ports:
      - "8000:5000"
    build: ./services/api
    restart: always # or on-failure or unless

# volumes:
#   SQLite:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./data/sqlite

networks:
  transc:
    driver: bridge
