# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jeportie <jeportie@42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/12 17:28:24 by jeportie          #+#    #+#              #
#    Updated: 2025/07/12 17:28:49 by jeportie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:

  frontend:
    container_name: frontend
    volumes:
      - ./services/frontend:/app
    networks:
      - transc
    ports:
      - "3000:3000"
    build: ./services/frontend
    restart: always

  api:
    container_name: api
    volumes:
      - ./services/api:/app
    networks:
      - transc
    ports:
      - "8000:5000"
    build: ./services/api
    restart: always # or on-failure or unless

volumes:
  SQLite:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/SQLite

networks:
  transc:
    driver: bridge
