global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
