# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    openapi.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jeportie <jeportie@42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/09/08 13:01:22 by jeportie          #+#    #+#              #
#    Updated: 2025/09/08 13:08:02 by jeportie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

openapi: 3.0.3
info:
  title: ft_transcendence API
  version: 1.0.0
  description: >
    API for the ft_transcendence project.  
    Provides authentication, health monitoring, and game-related endpoints.
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /api/health:
    get:
      summary: Health check
      description: Returns the current health status of the API and database.
      tags: [System]
      operationId: getHealth
      responses:
        "200":
          description: Health status response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  updated_at:
                    type: string
                    format: date-time
                    nullable: true
                    example: "2025-09-05T14:30:00.000Z"

  /api/auth:
    post:
      summary: Authenticate user
      description: Authenticates a user with username and password.
      tags: [Authentication]
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user, pwd]
              properties:
                user:
                  type: string
                  example: jeportie
                pwd:
                  type: string
                  example: secret123
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    description: JWT access token
        "400":
          description: Missing credentials
        "401":
          description: Invalid credentials

  /api/me:
    get:
      summary: Get authenticated user
      description: >
        Returns the authenticated user’s profile from the database.  
        Requires a valid Bearer token.
      tags: [Authentication]
      operationId: getMe
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Authenticated user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  me:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      username:
                        type: string
                        example: jeportie
                      email:
                        type: string
                        example: jerome@example.com
                      role:
                        type: string
                        example: player
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-09-05T14:00:00.000Z"
        "401":
          description: Unauthorized (invalid or missing token)

  /api/admin/users:
    get:
      summary: List all users (admin only)
      description: >
        Retrieves the full list of registered users.  
        Access restricted to `admin` role.
      tags: [Admin]
      operationId: listUsers
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  succes:
                    type: boolean
                    example: true
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        username:
                          type: string
                          example: jeportie
                        email:
                          type: string
                          example: jerome@example.com
                        role:
                          type: string
                          example: admin
                        created_at:
                          type: string
                          format: date-time
                          example: "2025-09-05T14:00:00.000Z"
        "401":
          description: Unauthorized (missing/invalid token)
        "403":
          description: Forbidden (not an admin)
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
